<a href="https://colab.research.google.com/github/snanditachn/Nandita.S_cts/blob/main/24_8_ex_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1:

Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

In [10]:
import numpy as np

In [11]:
list1 = [7, 9, 65, 33, 85, 99]

In [12]:
arr1 = np.array(list1)

In [13]:
print (arr1)

[ 7  9 65 33 85 99]


Generate a matrix (2D numpy array) of the values:
120
235
401

In [14]:
list2 = [1,2,0,2,3,5,4,0,1]

In [15]:
arr2 = np.array(list2)

In [16]:
arr2= arr2.reshape(3, 3)

In [17]:
print(arr2)

[[1 2 0]
 [2 3 5]
 [4 0 1]]


Change the dimensions of this array to another permitted shape

In [18]:
arr2= arr2.reshape(9,1)
print (arr2)

[[1]
 [2]
 [0]
 [2]
 [3]
 [5]
 [4]
 [0]
 [1]]


# Exercise 2:

Create an array of string numbers, but use dtype to make it an array of floats.

In [28]:
arr1_with_strings = np.array(['1', '4', '16', '22', '44', '66'])
arr1_with_strings

array(['1', '4', '16', '22', '44', '66'], dtype='<U2')

In [29]:
print(arr1_with_strings.astype(float))

[ 1.  4. 16. 22. 44. 66.]


Transpose the matrix, printing the new size and shape.

In [30]:
arr2.shape = (1,9)
print(arr2, "\n")
print(arr2.T)

[[1 2 0 2 3 5 4 0 1]] 

[[1]
 [2]
 [0]
 [2]
 [3]
 [5]
 [4]
 [0]
 [1]]


Use the .astype() method to convert the array to boolean

In [31]:
print(arr1_with_strings.astype(bool))

[ True  True  True  True  True  True]


# Exercise 3:

Create a numpy array with 50 zeros

In [34]:
arr0= np.zeros(50)
arr0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a np array of 2 repeated 20 times

In [37]:
arrof2 =np.full(20,2)

In [38]:
arrof2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Create a numpy array from 0 to 2 pi in steps of 0.1

In [40]:
 arrofpi= np.arange(start=0, stop=6.283, step=0.1)  # pi value is 6.283
 arrofpi

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

Get the first five values

In [44]:
arrofpi[:5]

array([0. , 0.1, 0.2, 0.3, 0.4])

Get the last 3 values

In [45]:
arrofpi[-3:]

array([6. , 6.1, 6.2])

Get the 4th value to the 7th value

In [47]:
arrofpi [4:8]

array([0.4, 0.5, 0.6, 0.7])

 Reverse it

In [48]:
revarrofpi =np.flip(arrofpi)

In [49]:
revarrofpi

array([6.2, 6.1, 6. , 5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5. ,
       4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4. , 3.9, 3.8, 3.7,
       3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4,
       2.3, 2.2, 2.1, 2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1,
       1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

 Only keep every 4th element

In [51]:
revarrofpi4 = arrofpi[0::4]
revarrofpi4

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8,
       5.2, 5.6, 6. ])

Get every 2nd element, starting from the last and moving backwards.

In [54]:
arrofpi [-1::-2]

array([6.2, 6. , 5.8, 5.6, 5.4, 5.2, 5. , 4.8, 4.6, 4.4, 4.2, 4. , 3.8,
       3.6, 3.4, 3.2, 3. , 2.8, 2.6, 2.4, 2.2, 2. , 1.8, 1.6, 1.4, 1.2,
       1. , 0.8, 0.6, 0.4, 0.2, 0. ])

# Exercise 4

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [55]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [56]:
nums = np.arange(0, 4, 0.2555)

In [57]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


# Exercise 5

Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.

In [60]:
dice = np.random.choice([0,1,2,3,4,5,6], 10)
dice

array([6, 6, 5, 5, 3, 3, 5, 5, 3, 2])

Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails

In [64]:
notfair = np.random.choice([0,1,1], 10)
notfair

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1])